version: '3'
services:
  client:
    container_name: yohdev-starter_react
    restart: always
    ports:
      - 3000:3000
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    networks:
      - internal
  api:
    container_name: yohdev-starter_api
    restart: always
    ports:
      - 8080:8080
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    networks:
      - internal
networks:
    internal:
        driver: bridge